FROM node:12.8.0
EXPOSE 3000

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
#RUN npm install react-scripts@3.0.1 -g --silent

COPY . .

# start app
#CMD ["npm", "start"]
